# Site settings
title: Projekt Zespołowy - II UJ
email: ksi@uj.edu.pl
description: >
  Projekt Zespołowy w Instytucie Informatyki Uniwersytetu Jagiellońskiego
  - wszystko co potrzebujesz wiedzieć w jednym miejsuc.
baseurl: ""
url: "https://pz.ksi.ii.uj.edu.pl"
github_username: KSIUJ
permalink: none

collections:
  companies:
    output: true

# Build settings
markdown: kramdown
